### ISSUE TITLE
samlp:LogoutResponse signature verification fails with ADFS

### ISSUE THREAD

**Issue by m6a-UdS** [onelogin/python-saml#139] opened 2016-05-19 15:08 UTC
Hello,

I have an issue with my ADFS infrastructure: When I try to use the Single Sign-Out functionality of the python-saml library, I get an error saying that `'Signature validation failed. Logout Response rejected'`.

I don't think it's a certificate issue because the login ( `samlp:AuthnRequest` ) works well and stops working (as expected) if I set a wrong certificate.

The StatusCode I get from the server is `<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>` so my guess is that the issue is really on the SP side.

The binding is set to `Redirect` on both SP and IDP sides.

Here is a sample of a logout request/response:
```
<samlp:LogoutRequest ID="ONELOGIN_xyzxyz" Version="2.0" IssueInstant="2016-05-18T18:58:23Z" Destination="https://ad.corp.company.com/adfs/ls">
<saml:Issuer>https://app.sp.io/saml2/metadata/</saml:Issuer>
<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">user@company.com</saml:NameID>
<samlp:SessionIndex>_xyz-xyz-xyz</samlp:SessionIndex>
</samlp:LogoutRequest>
```

```
<samlp:LogoutResponse ID="_xyz-xyz-xyz" Version="2.0" IssueInstant="2016-05-18T18:58:23.687Z" Destination="https://app.sp.io/saml2/sls/" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="ONELOGIN_xyzxyz">
<Issuer>http://ad.corp.company.com/adfs/services/trust</Issuer>
<samlp:Status>
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
</samlp:Status>
</samlp:LogoutResponse>
```

With other query parameters:
```
*SAMLResponse:*fZLNasMwEIR...
*RelayState:*https://app.sp.io:8000/logout/
*Signature:*oAI7sHX6jdCio...
*SigAlg:*http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
```
I also tried with `http://www.w3.org/2000/09/xmldsig#sha1` without success. Any idea why the SLS signature verification would fail?

Thank you!

**Comment by pitbulk** [comment] 2016-05-19 15:46
Can you try to validate your LogoutResponse at https://www.samltool.com/validate_logout_res.php ?
(Take the base64 encode version and decode at https://www.samltool.com/decode.php, then paste it on the validation and fill required fields.)

**Comment by m6a-UdS** [comment] 2016-05-19 16:05
Thank you for your quick answer!

I get the same error on the test website: `Signature validation failed. Logout Response rejected`

Also if it is useful, in my code, `auth.get_errors()` contains only `['invalid_logout_response']`.

**Comment by pitbulk** [comment] 2016-05-19 16:35
This message is showed when the [Signature validation fails](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/logout_response.py#L132).

Can you compare the values you got from ADFS and what is used on the [validate_binary_sign](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/logout_response.py#L131) call?

**Comment by m6a-UdS** [comment] 2016-05-19 19:48
I don't have access to modify the source libraries of this machine, unfortunately; But I can try to validate the signature "offline" and here is what it gives me:
`print OneLogin_Saml2_Utils.validate_binary_sign(signed_query, signature, cert, sign_alg, debug=True)`

```
app.c:1254(xmlSecOpenSSLAppCertLoadBIO) subject=PEM_read_bio_X509_AUX errno=4
app.c:924(xmlSecOpenSSLAppKeyFromCertLoadBIO) subject=xmlSecOpenSSLAppCertLoadBIO
app.c:334(xmlSecOpenSSLAppKeyLoadBIO) subject=xmlSecOpenSSLAppKeyFromCertLoadBIO
app.c:153(xmlSecOpenSSLAppKeyLoad) subject=xmlSecOpenSSLAppKeyLoadBIO msg=filename=/var/folders/k1/qckyp8bj2djg4szf8zgn_q_r86xkbt/T/tmpkppY0t;errno=0
```

The first line seems to point to an error; Is it possible that xmlSec does not like my certificate? (Which would be weird, as I said the AuthnRequest gets verified just fine with the very same singing X509 cert...)

Thank you!

**Comment by m6a-UdS** [comment] 2016-05-19 22:18
Update: Never mind my previous message, my cert was not formatted properly (missing head/foot `-----BEGIN/END CERTIFICATE-----` )

Now I just have `signatures.c:493(xmlSecOpenSSLEvpSignatureVerify) obj=rsa-sha256 subject=EVP_VerifyFinal msg=signature do not match errno=18` to solve ;-)

**Comment by pitbulk** [comment] 2016-05-20 06:42
Is strange since it is working on other environments.

**Comment by pitbulk** [comment] 2016-05-20 11:15
I found that this Issue is related with another issues that an user reported.
Follow the trace: https://github.com/onelogin/python-saml/issues/33

**Comment by m6a-UdS** [comment] 2016-05-24 03:17
Thank you for the follow-up and sorry for the late reaction; 

Yes it seems very much like the same problem; Do you know what is supposed to be signed by ADFS? I will continue where anthony left by testing with raw openssl signature; From what I understand from the code, it should be the GET query params without the Signature part; I will check the docs to be sure, maybe Microsoft has something different with their implementation?

**Comment by pitbulk** [comment] 2016-05-24 15:46
Review [3.4.4.1DEFLATE Encoding](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) 

Microsoft must follow the SAML standard so I think the problem is related to any modification on the GET parameters between the IdP and the SP or some signature algorithm difference.

**Comment by m6a-UdS** [comment] 2016-05-24 18:45
Update: The signature verifies correctly with:

> openssl dgst -verify pubkey.pem -signature signature.bin response.txt
> Verified OK

`pubkey.pem`: Extracted PEM from the x509 cert
`signature.bin`: Base64-decoded value of the signature parameter
`response.txt`: URL-Encoded response data from the HTTP Request, without the `Signature` parameter

I will dig deeper in the code to see where these parameters are different...

**Comment by pitbulk** [comment] 2016-05-24 19:41
Thanks, let me know if you figure out what is going on or if you need specific help.

**Comment by m6a-UdS** [comment] 2016-05-24 19:46
Thanks! I verified that the signature also works with `OneLogin_Saml2_Utils.validate_binary_sign(query, signature, cert, sign_alg, debug=True)` which works.

My main hypothesis is that Django URL-Decodes the request parameters before validating; More about this later ;-)

**Comment by m6a-UdS** [comment] 2016-05-24 20:56
Is it possible that the problem would come from the comment here? https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L1130

> The encoding used by ADFS 3.0 is not compatible with python's quote_plus (ADFS produces lower case hex numbers and quote_plus produces upper case hex numbers)

**Comment by pitbulk** [comment] 2016-05-24 22:15
Thanks :)

**Comment by m6a-UdS** [comment] 2016-05-26 15:06
https://github.com/onelogin/python-saml/pull/144

This works in my environment. Should be backward-compatible ;-)

**Comment by NejcZupec** [comment] 2016-05-31 10:57
@m6a-UdS Great work! I have encountered the same issue. I pulled your pull request and tested it in my environment and it works :) :+1:

**Comment by pitbulk** [comment] 2016-06-03 21:50
It was merged,

can you review if signature created by this toolkit, are validated on ADFS 3.0?

**Closed by pitbulk** 2016-06-03 21:50 UTC

**Comment by m6a-UdS** [comment] 2016-06-06 20:07
I updated my project with the PyPI release and signatures do verify correctly 👍

**Comment by pitbulk** [comment] 2016-06-06 20:08
Great! thanks for contribute and for checking that, now you are part of the Python SAML Tookit ;)
